Convert source_rvm  to version_manager_fix
Addresses #5.

Check which ruby_version_manager is in use then take the appropriate action.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -212,20 +212,32 @@ function check_ruby_version_manager {
 }
 
 
-function source_rvm {
+function version_manager_fix {
 
-  if [[ "${target_os}" == "Kali" ]]; then 
-    # shellcheck disable=SC1091
-    source "/etc/profile.d/rvm.sh"
+  if [[ "${ruby_version_manager}" == "rvm" ]]; then
 
-  elif [[ "${target_os}" == "Debian" ]]; then
-    # shellcheck disable=SC1090
-    source "${HOME}/.rvm/scripts/rvm"
+    if [[ "${target_os}" == "Kali" ]]; then 
+      # shellcheck disable=SC1091
+      source "/etc/profile.d/rvm.sh"
 
-  else 
-    echo -e "[${FATAL}] Compatibility issue"
+    elif [[ "${target_os}" == "Debian" ]]; then
+      # shellcheck disable=SC1090
+      source "${HOME}/.rvm/scripts/rvm"
+
+    else 
+      echo -e "[${FATAL}] Compatibility issue"
+      exit 1
+    fi
+
+  elif [[ "${ruby_version_manager}" == "rbenv" ]]; then
+    
+    "$HOME"/.rbenv/bin/rbenv init
+    
+  else
+     # Totally fucked it
+    echo -e "[${FATAL}] Unknown error"
     exit 1
-  fi
+  fi 
 }
 
 
@@ -253,7 +265,7 @@ function install_rvm {
     echo -e "[${INFO}] Getting and installing RVM"
     if curl -sSL https://get.rvm.io | bash -s stable ; then
       ruby_version_manager="rvm"
-      source_rvm
+      version_manager_fix
       echo -e "[${PASS}] Installed RVM"
       
     else
@@ -264,7 +276,7 @@ function install_rvm {
 
   else
     ruby_version_manager="rvm"
-    source_rvm
+    version_manager_fix
     echo -e "[${PASS}] RVM already installed"
   fi
 }
@@ -275,7 +287,7 @@ function rvm_install_ruby {
   # Install Ruby ${ruby_version} via RVM
   # Set Ruby ${ruby_version} as default for RVM 
 
-  source_rvm
+  version_manager_fix
 
   if rvm list default | grep -q "${ruby_version}" ; then
     echo -e "[${PASS}] RVM default Ruby version already ${ruby_version}"
@@ -351,7 +363,7 @@ function install_beef {
   (
     cd beef || exit
 
-  source_rvm
+    version_manager_fix
 
     echo -e "[${INFO}] Installing Bundler"
     if gem install bundler ; then
@@ -361,9 +373,9 @@ function install_beef {
       exit 1
     fi
 
-    source_rvm
     if bundle install --without test development ; then
       echo -e "[${PASS}] Sucessfully installed BeEF"
+      version_manager_fix
       exit 0
     else
       echo -e "[${FATAL}] Failed to install BeEF"
