Refactor

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,6 +24,9 @@ PASS="\\033[1;32mPASS\\033[0m"
 INFO="\\033[1;36mINFO\\033[0m"
 
 
+### UTILITY FUNCTIONS ###
+
+
 function check_compatibility {
 
   # Check if Distribution is Kali or Debian
@@ -75,50 +78,6 @@ function check_compatibility {
     echo -e "[${FATAL}] Only tested on Kali/ Debian"
     exit 1
   fi
-}
-
-
-function install_dependencies {
-
-  # Install required dependencies via apt-get
-  # TODO: Check target_os to install different deps depending on the OS
-  
-  local all_deps=(curl git nodejs python3 python3-pip \
-    build-essential openssl libreadline-dev zlib1g \
-    zlib1g-dev libssl1.0-dev libyaml-dev libsqlite3-0 \
-    libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
-    autoconf libc6-dev libncurses5-dev automake libtool \
-    bison)
-  local needed_deps=()
-  
-  for package in "${all_deps[@]}"; do
-    if ! dpkg-query -W -f='${Status}' "${package}" 2>/dev/null | grep -q 'install ok installed'; then
-      needed_deps+=("${package}")
-    fi
-  done
-
-  if ! [ ${#needed_deps[@]} -eq 0 ]; then
-    echo -e "[${INFO}] Installing ${#needed_deps[@]} dependencies via apt-get"
-    sleep 2
-    sudo apt-get -qq update
-  else
-    echo -e "[${PASS}] All dependencies already installed"
-    return 0 
-  fi
-
-  for package in "${needed_deps[@]}"; do
-    echo -e "[${INFO}] Installing ${package}"
-    if ! sudo apt-get -qq install -y "${package}" >/dev/null; then
-      echo -e "[${FATAL}] Failed to install ${package}"
-      exit 1
-    fi
-  done
-
-  # Clean up any redundant dependencies
-  sudo apt-get -qq autoremove -y >/dev/null
-
-  echo -e "[${PASS}] Dependencies installed"
-  return 0
 }
 
 
@@ -213,6 +172,29 @@ function check_ruby_version_manager {
 }
 
 
+function rvm_fix {
+  
+  if [[ "${target_os}" == "Kali" ]]; then
+    # shellcheck disable=SC1091
+    source "/etc/profile.d/rvm.sh"
+
+  elif [[ "${target_os}" == "Debian" ]]; then
+    # shellcheck disable=SC1090
+    source "${HOME}/.rvm/scripts/rvm"
+
+  else
+    echo -e "[${FATAL}] Compatibility issue"
+    exit 1
+  fi
+}
+
+
+function rbenv_fix {
+
+  "$HOME"/.rbenv/bin/rbenv init
+}
+
+
 function version_manager_fix {
 
   if [[ -z "${ruby_version_manager}" ]]; then
@@ -243,25 +225,50 @@ function version_manager_fix {
 }
 
 
-function rvm_fix {
+### END UTILITY FUNCTIONS ###
+
+
+function install_dependencies {
+
+  # Install required dependencies via apt-get
+  # TODO: Check target_os to install different deps depending on the OS
   
-  if [[ "${target_os}" == "Kali" ]]; then
-    # shellcheck disable=SC1091
-    source "/etc/profile.d/rvm.sh"
+  local all_deps=(curl git nodejs python3 python3-pip \
+    build-essential openssl libreadline-dev zlib1g \
+    zlib1g-dev libssl1.0-dev libyaml-dev libsqlite3-0 \
+    libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
+    autoconf libc6-dev libncurses5-dev automake libtool \
+    bison)
+  local needed_deps=()
+  
+  for package in "${all_deps[@]}"; do
+    if ! dpkg-query -W -f='${Status}' "${package}" 2>/dev/null | grep -q 'install ok installed'; then
+      needed_deps+=("${package}")
+    fi
+  done
 
-  elif [[ "${target_os}" == "Debian" ]]; then
-    # shellcheck disable=SC1090
-    source "${HOME}/.rvm/scripts/rvm"
-
+  if ! [ ${#needed_deps[@]} -eq 0 ]; then
+    echo -e "[${INFO}] Installing ${#needed_deps[@]} dependencies via apt-get"
+    sleep 2
+    sudo apt-get -qq update
   else
-    echo -e "[${FATAL}] Compatibility issue"
-    exit 1
+    echo -e "[${PASS}] All dependencies already installed"
+    return 0 
   fi
-}
 
-function rbenv_fix {
+  for package in "${needed_deps[@]}"; do
+    echo -e "[${INFO}] Installing ${package}"
+    if ! sudo apt-get -qq install -y "${package}" >/dev/null; then
+      echo -e "[${FATAL}] Failed to install ${package}"
+      exit 1
+    fi
+  done
 
-  "$HOME"/.rbenv/bin/rbenv init
+  # Clean up any redundant dependencies
+  sudo apt-get -qq autoremove -y >/dev/null
+
+  echo -e "[${PASS}] Dependencies installed"
+  return 0
 }
 
 
